# Generated by Django 5.0.7 on 2024-08-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_article_image_url_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='image_url',
        ),
    ]
